name: Access Repo java-maven-pipeline-example and List Files

on:
  push:
    branches:
      - "test/deployKey"
  workflow_dispatch:

jobs:
  test-repo-b-access:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout broker-JWT sync repo
        uses: actions/checkout@v4

      - name: Setup SSH Key for Repo java-maven-pipeline-example
        env:
          REPO_DEPLOY_KEY: ${{ secrets.TEST_DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$REPO_DEPLOY_KEY" > ~/.ssh/repo_deploy_key
          chmod 600 ~/.ssh/repo_deploy_key
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Clone Repo java-maven-pipeline-example
        run: |
          GIT_SSH_COMMAND='ssh -i ~/.ssh/repo_deploy_key' git clone git@github.com:bcgov/java-maven-pipeline-example.git maven-pipeline

      - name: List Files in Repo java-maven-pipeline-example
        working-directory: maven-pipeline
        run: |
          echo "Files in repo java-maven-pipeline-example:"
          ls -R

      - name: Configure Maven Settings with GitHub Packages
        run: |
          mkdir -p ~/.m2
          cat <<EOF > ~/.m2/settings.xml
          <settings>
            <servers>
              <server>
                <id>github</id>
                <configuration>
                  <httpHeaders>
                    <property>
                      <name>Authorization</name>
                      <value>Bearer $GITHUB_TOKEN</value>
                    </property>
                  </httpHeaders>
                </configuration>
              </server>
            </servers>
          </settings>
          EOF

      - name: Download Maven Package from Repo B
        run: |
          mvn dependency:get -DrepoUrl="https://maven.pkg.github.com/bcgov/java-maven-pipeline-example" \
                             -Dartifact=bcgov.example:java-maven-pipeline-example:1.0.1-SNAPSHOT \
                             -Dtransitive=false



